"""image

Revision ID: 627efa6e1d60
Revises: 92c79c8d95cb
Create Date: 2024-01-26 21:50:27.373038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627efa6e1d60'
down_revision = '92c79c8d95cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('classes', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_image')
    # ### end Alembic commands ###
