"""test

Revision ID: 92c79c8d95cb
Revises: 
Create Date: 2024-01-20 20:35:03.293201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c79c8d95cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sentimen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review', sa.String(length=1052), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_sentimen')
    # ### end Alembic commands ###
